openapi: 3.1.0
info:
  title: Bloqueo/Desbloqueo de Expediente (DIC)
  version: "1.0.1"
  description: |
    Servicio para **bloquear o desbloquear** un expediente GDE.

    Reglas de operación (según PDF oficial):
    - Tipo servicio: REST
    - Método: **POST**
    - Observaciones: Servicio disponible en **EDI Mendoza**.
    - Restricciones:
      - Autorización del subsistema productor `capaserviciosgx`.
      - Encabezados X-Road:
        - `X-Road-Client` (**obligatorio**): Cliente autorizado.
        - `X-Road-UserId`: Identificación del usuario que inicia la solicitud.
        - `X-Road-Issue` (**obligatorio**): Identificador único y descentralizado (**UUID v4** recomendado).
          - Se sugiere anteponer nombre de la app: `NombreApp-<uuid>`.
          - En cadenas de llamados: `App2-App1-<uuid>`.
    - Producción: **no indicado en el documento oficial**.
servers:
  - url: https://{nodoXroad}/r1/mendoza/DIC/002/capaserviciosgx
    description: Ambiente Testing (X-Road)
    variables:
      nodoXroad:
        description: Nodo X-Road del entorno.
        default: xroad-test.mendoza.gov.ar
tags:
  - name: GDE
paths:
  /GDEBloqueoTST:
    post:
      tags: [GDE]
      summary: Bloquea o desbloquea un expediente
      description: Realiza la operación de **bloqueo (B)** o **desbloqueo (D)** sobre el expediente indicado.
      operationId: bloquearDesbloquearExpediente
      parameters:
        - $ref: '#/components/parameters/XRoadClient'
        - $ref: '#/components/parameters/XRoadUserId'
        - $ref: '#/components/parameters/XRoadIssue'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBloqueo'
            examples:
              Ejemplo_Bloqueo:
                value:
                  CodigoExpedienteElectronico: "EX-2021-00060484--GDEMZA-CGPROV%23MHYF"
                  OperacionBloqueo: "B"
              Ejemplo_Desbloqueo:
                value:
                  CodigoExpedienteElectronico: "EX-2021-00060484--GDEMZA-CGPROV%23MHYF"
                  OperacionBloqueo: "D"
      responses:
        "200":
          description: Respuesta de éxito o de error de aplicación (único HTTP documentado).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SDTResultado'
              examples:
                Exito_Bloqueo:
                  $ref: '#/components/examples/Exito_Bloqueo'
                Error_Expediente_NoValido:
                  $ref: '#/components/examples/Error_Expediente_NoValido'
                Error_Filtros_Vacios_CodigoExpediente:
                  $ref: '#/components/examples/Error_Filtros_Vacios_CodigoExpediente'
                Error_Filtros_NoValido_OperacionBloqueo:
                  $ref: '#/components/examples/Error_Filtros_NoValido_OperacionBloqueo'
components:
  parameters:
    XRoadClient:
      name: X-Road-Client
      in: header
      required: true
      schema: { type: string }
      description: Cliente autorizado para su consumo (X-Road).
    XRoadUserId:
      name: X-Road-UserId
      in: header
      required: false
      schema: { type: string }
      description: Identificación del usuario que inicia la solicitud.
    XRoadIssue:
      name: X-Road-Issue
      in: header
      required: true
      schema:
        type: string
      description: |
        Identificador único de la transacción. **UUID v4** recomendado.
        Se permiten prefijos/cadenas:
        - `NombreApp-<uuid>`
        - `App2-App1-<uuid>`
  schemas:
    RequestBloqueo:
      type: object
      properties:
        CodigoExpedienteElectronico:
          type: string
          maxLength: 200
          description: |
            Código del expediente electrónico.
            Si contiene `#`, usar percent-encoding: `#` → `%23`.
          example: EX-2021-00060484--GDEMZA-CGPROV%23MHYF
        OperacionBloqueo:
          type: string
          maxLength: 1
          description: Operación a realizar.
          enum: ["B", "D"]
      required: [CodigoExpedienteElectronico, OperacionBloqueo]
    Message:
      type: object
      properties:
        Id:
          type: string
          maxLength: 128
        Type:
          type: integer
          enum: [0, 1, 2, 3]
        Description:
          type: string
          maxLength: 256
      required: [Id, Type, Description]
    SDTResultado:
      type: object
      properties:
        Flag:
          type: string
          enum: ["C", "E"]
          description: |
            Estado del llamado del servicio.
            `C`: se encontraron datos (condición de éxito).
            `E`: condición sin datos/errores.
        Messages:
          type: array
          items: { $ref: '#/components/schemas/Message' }
      required: [Flag, Messages]
  examples:
    Exito_Bloqueo:
      summary: Caso de éxito (bloqueo realizado)
      value:
        Flag: "C"
        Messages:
          - Description: "El expediente electrónico se ha bloqueado correctamente."
            Id: "ExpedienteBloqueado"
            Type: 0
    Error_Expediente_NoValido:
      summary: Error de aplicación - expediente inexistente/no válido
      value:
        Flag: "E"
        Messages:
          - Description: "El expediente ingresado no existe en sistema GDE."
            Id: "Expediente_NoValido"
            Type: 1
    Error_Filtros_Vacios_CodigoExpediente:
      summary: Error de aplicación - código vacío
      value:
        Flag: "E"
        Messages:
          - Description: "Debe completar el código del expediente a consultar."
            Id: "Filtros_Vacios_CodigoExpediente"
            Type: 1
    Error_Filtros_NoValido_OperacionBloqueo:
      summary: Error de aplicación - operación no válida/ausente
      value:
        Flag: "E"
        Messages:
          - Description: "Debe completar la operación a realizar: BLOQUEO (B) / DESBLOQUEO (D)."
            Id: "Filtros_NoValido_OperacionBloqueo"
            Type: 1
